Kubernetes-security
otus-kuber-2020-11/mdasaev_platform pull request #4
Opened 2020-12-22 21:11 UTC by mdasaev

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2020-12-28 08:53 UTC, Jasstkn requested changes
Добрый день.
Тесты не прошли успешно, обратите внимание на ошибки:
- RBAC: role.rbac.authorization.k8s.io "pod-reader" not found
- +kubectl auth can-i list pods --as system:serviceaccount:prometheus:carol -n prometheus

В тестах выполняются следующие проверки: 
```
# carol should not have deployments permissions in default namespace
kubectl auth can-i get deployments --as system:serviceaccount:prometheus:carol && exit 2

# but should be able to list pods in prometheus namespace
kubectl auth can-i list pods --as system:serviceaccount:prometheus:carol -n prometheus || exit 2
```

2021-01-12 12:26 UTC, Jasstkn commented on kubernetes-security/task02/code_task02.yaml
> +  name: task02
Вот здесь нужно namespace указать, иначе все объекты ищутся в немспейсе default

2021-01-12 12:47 UTC, mdasaev commented on kubernetes-security/task02/code_task02.yaml
> +  name: task02
> Вот здесь нужно namespace указать, иначе все объекты ищутся в немспейсе default

готово

2021-01-22 18:54 UTC, Jasstkn commented on kubernetes-security/task02/code_task02.yaml
> +  name: task02
```
no - RBAC: role.rbac.authorization.k8s.io "admin" not found
+ exit 3
```

2021-01-22 18:55 UTC, Jasstkn commented on kubernetes-security/task03/janerole.yaml
> +  name: admin
скорее всего админ у вас ClusterRole

2021-01-22 18:56 UTC, Jasstkn requested changes
Оставила комментарий

2021-01-26 16:31 UTC, mdasaev commented on kubernetes-security/task03/janerole.yaml
> +  name: admin
> скорее всего админ у вас ClusterRole

почему?

Задание звучит так:
Создать Namespace dev
Создать Service Account jane в Namespace dev Дать jane роль admin в рамках Namespace dev

2021-01-31 19:07 UTC, mdasaev commented
> Оставила комментарий

скорее всего админ у вас ClusterRole
 
 
почему?

Задание звучит так:
Создать Namespace dev
Создать Service Account jane в Namespace dev Дать jane роль admin в рамках Namespace dev

2021-02-02 05:24 UTC, Jasstkn commented on kubernetes-security/task03/janerole.yaml
> +  name: admin
Такой роли в немспейсе нет.

2021-02-04 08:45 UTC, Jasstkn commented
> > @Jasstkn  Оставила комментарий
> 
> скорее всего админ у вас ClusterRole
> 
> почему?
> 
> Задание звучит так:
> Создать Namespace dev
> Создать Service Account jane в Namespace dev Дать jane роль admin в рамках Namespace dev

как и написала, такой роли у вас нет в немспейсе:
https://github.com/otus-kuber-2020-11/mdasaev_platform/pull/4/checks?check_run_id=1829202847#step:4:104

2021-02-04 08:58 UTC, mdasaev commented
Да, я проверил. Использовал кластерную роль, но указал бинд неправильно. Исправлю и желаю апдейт.
On Feb 4, 2021, 11:45 AM +0300, Maria Kotlyarevskaya <notifications@github.com>, wrote:
> > > @Jasstkn Оставила комментарий
> > скорее всего админ у вас ClusterRole
> > почему?
> > Задание звучит так:
> > Создать Namespace dev
> > Создать Service Account jane в Namespace dev Дать jane роль admin в рамках Namespace dev
> как и написала, такой роли у вас нет в немспейсе:
> https://github.com/otus-kuber-2020-11/mdasaev_platform/pull/4/checks?check_run_id=1829202847#step:4:104
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-04-05 18:35 UTC, Jasstkn commented
@mdasaev помощь нужна? :)

2021-04-05 19:34 UTC, merged