Kubernetes controllers
otus-kuber-2020-11/mdasaev_platform pull request #5
Opened 2021-01-11 10:21 UTC by mdasaev

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist:
 - [ ] Выставлен label с темой домашнего задания

2021-01-11 18:06 UTC, Jasstkn requested changes
Добрый день. Деплоймент с фронтендом не стартует - пробы не проходят.

2021-01-11 22:53 UTC, mdasaev commented
Как я могу сделать реопен для ПР?

2021-01-11 22:54 UTC, mdasaev commented
> Добрый день. Деплоймент с фронтендом не стартует - пробы не проходят.

Как я могу сделать реопен для ПР?

2021-01-12 10:42 UTC, Jasstkn approved these changes
Теперь тесты проходят успешно - аппрув

2021-01-12 10:43 UTC, merged